### ISSUE TITLE
Support variadric in arguments in `grpcui`

### ISSUE THREAD

**Issue by mkatychev** [knox-networks/grpcui#2]
It's worth investigating the lift in addressing the issue below by passing in multiple endpoints to `grpcui`:
https://github.com/fullstorydev/grpcui/issues/14

So that the call below
`$ grpcui issuer-001.sandbox6.knoxnetworks.io:443`
<img width="741" alt="image" src="https://user-images.githubusercontent.com/11223234/209195210-f040b110-85a4-49fa-ae6b-9c0f09777585.png">

Can support a dropdown of connections:
`$ grpcui issuer-001.sandbox6.knoxnetworks.io:443 faucet-001.sandbox6.knoxnetworks.io:443 authority.sandbox6.knoxnetworks.io:443 gateway.sandbox6.knoxnetworks.io:443`
<img width="882" alt="image" src="https://user-images.githubusercontent.com/11223234/209195303-d5307b55-0ad9-4105-bf99-62df1a538405.png">

grpcui essentially uses `grpcurl` under the hood so in theory modifying the `addr` argument should allow us to create/maintain  a`*grpc.ClientConn` per endpoint:
https://github.com/fullstorydev/grpcui/blob/4ddf8a02af25e2459bac9531d88ec9cb93f5414b/cmd/grpcui/grpcui.go#L1030-L1069

**Comment by fkim7** [comment]
It may be a challenge to be able to figure out endpoints newly created issuers/faucets/treasuries on the fly.   As mitigation we can start with just doing 001 for now- ex issuer-001. FYI @mkatychev @spurohit42

**Comment by fkim7** [comment]
Also please exclude control plane from the endpoints as well.

**Comment by echenknox** [comment]
To load comments, we need to specify where is the "-proto" file and "-import-path" for each target service.
Then the command line is going to be convoluted. Example of one single target service with command line is like this:
```
grpcui -proto protos/auth_api/v1/auth.proto -import-path protos/auth_api/v1/ -base-path /auth-mgmt auth-mgmt.sandbox6.knoxnetworks.io:443
```
With multiple services, we can't use the command line. It can't build a relationship between each flag. 
We will have to change the service with a configuration file.

**Comment by fkim7** [comment]
@codemile FYI the thread where we assumed we'll just be doing 001 for now.. will need to revisit
